# Generated by Django 3.2 on 2022-11-03 02:44

import Ciudadano.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Nivel',
            },
        ),
        migrations.CreateModel(
            name='Tiposolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de solicitud')),
            ],
            options={
                'verbose_name': 'Tipo de solicitud',
                'verbose_name_plural': 'TIpo de solicitud',
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'TIpo de documentos',
            },
        ),
        migrations.CreateModel(
            name='Pqrsd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='2.Nombre del remitente')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='3.Apellidos del remitente')),
                ('identification', models.CharField(blank=True, max_length=30, null=True, verbose_name='5.Identificación')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='6.Municipio')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='7.Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='8.Celular')),
                ('asunto', models.CharField(blank=True, max_length=400, null=True, verbose_name='9.Asunto ')),
                ('solicitud', models.TextField(blank=True, null=True, verbose_name='10.Descripción Solicitud')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pqrsd/file', validators=[Ciudadano.models.file_size], verbose_name='11.Archivo adjunto')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tiposolicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Ciudadano.tiposolicitud', verbose_name='1.Tipo de solicitud')),
                ('type_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Ciudadano.typedocument', verbose_name='4.Tipo de documento')),
            ],
            options={
                'verbose_name': 'Informe PQRSD',
                'verbose_name_plural': 'Informe PQRSD',
            },
        ),
        migrations.CreateModel(
            name='EncuestaTransparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encontro', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='1. Encontró la información que buscaba?:')),
                ('noencontro', models.CharField(blank=True, max_length=100, null=True, verbose_name='2. Si no la encontró especifique en este espacio ¿qué buscaba?')),
                ('facil', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='3. ¿Le resultó fácil la ruta de acceso a la información?:')),
                ('sugerencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='5. Si tiene alguna sugerencia escribanos en el siguiente espacio, recuerde que su opinión es muy importante para mejorar nuestro servicio.')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Ciudadano.nivel', verbose_name='4. ¿A nivel general, cómo define la información contenida en la página web?')),
            ],
            options={
                'verbose_name': 'Encuesta de satisfacción',
                'verbose_name_plural': 'Encuesta de satisfacción',
            },
        ),
    ]
