# Generated by Django 3.2 on 2022-11-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coro', models.TextField(blank=True, help_text='Coro', null=True, verbose_name='Coro')),
            ],
        ),
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('contact', models.CharField(help_text='Contacto', max_length=50, verbose_name='Contacto')),
                ('carge', models.CharField(help_text='Cargo', max_length=50, verbose_name='Cargo')),
                ('extension', models.TextField(help_text='Extension telefono', verbose_name='Extension telefono')),
                ('phone', models.IntegerField(help_text='Telefono', verbose_name='Telefono')),
                ('fax', models.CharField(help_text='Fax', max_length=20, verbose_name='Fax')),
                ('email', models.EmailField(help_text='Correo electronico', max_length=254, verbose_name='Correo electronico')),
            ],
            options={
                'verbose_name': ('Empleado',),
                'verbose_name_plural': 'Empleados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.TextField(blank=True, help_text='Función', null=True, verbose_name='Función')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Meta', null=True, verbose_name='Meta')),
                ('descripcion', models.TextField(blank=True, help_text='Altillanura', null=True, verbose_name='Altillanura')),
            ],
        ),
        migrations.CreateModel(
            name='MiVi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.CharField(blank=True, help_text='Mision', max_length=20, null=True, verbose_name='Mision')),
                ('descriptionmision', models.TextField(blank=True, help_text='Descripción mision', null=True, verbose_name='Descripción mision')),
                ('vision', models.CharField(blank=True, help_text='Vision', max_length=20, null=True, verbose_name='Vision')),
                ('descriptionvision', models.TextField(blank=True, help_text='Descripción Vision', null=True, verbose_name='Descripción Vision')),
            ],
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetive', models.TextField(blank=True, help_text='Objetivo', null=True, verbose_name='Objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('type', models.CharField(help_text='Tipo de sede', max_length=50, verbose_name='Tipo de sede')),
                ('adress', models.CharField(help_text='Direccion', max_length=50, verbose_name='Direccion')),
                ('city', models.TextField(help_text='Municipio', verbose_name='Municipio')),
                ('phone', models.IntegerField(help_text='Telefono', verbose_name='Telefono')),
                ('fax', models.CharField(help_text='Fax', max_length=20, verbose_name='Fax')),
                ('email', models.EmailField(help_text='Correo electronico', max_length=254, verbose_name='Correo electronico')),
            ],
            options={
                'verbose_name': ('Sede',),
                'verbose_name_plural': 'Sede',
                'ordering': ['id'],
            },
        ),
    ]
