# Generated by Django 3.2 on 2022-11-07 00:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Meta', null=True, verbose_name='Meta')),
                ('descripcion', models.TextField(blank=True, help_text='Altillanura', null=True, verbose_name='Altillanura')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Meta', null=True, verbose_name='Meta')),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
