# Generated by Django 3.2 on 2022-11-10 04:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('slug', models.CharField(blank=True, help_text='Slug', max_length=100, null=True, verbose_name='Slug')),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL Document')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ('Modulo',),
                'verbose_name_plural': 'Modulo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Normatividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=200, null=True, verbose_name='Nombre ')),
                ('name_archive', models.CharField(blank=True, help_text='Nombre de archivo', max_length=200, null=True, verbose_name='Nombre de archivo')),
                ('age', models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año')),
                ('month', models.CharField(blank=True, help_text='Mes', max_length=50, null=True, verbose_name='Mes')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('orden', models.PositiveBigIntegerField(blank=True, help_text='Orden', null=True, verbose_name='Orden')),
                ('modulo', models.CharField(blank=True, choices=[('LEYES', 'LEYES'), ('DECRETOS', 'DECRETOS'), ('RESOLUCIONES', 'RESOLUCIONES'), ('ORDENANZAS', 'ORDENANZAS'), ('ACUERDOS', 'ACUERDOS'), ('CODIGOS', 'CODIGOS'), ('MANUALES', 'MANUALES'), ('POLITICAS', 'POLITICAS')], max_length=30, null=True, verbose_name='Estado:')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL Document')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ('Normatividad',),
                'verbose_name_plural': 'Normatividad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Planeacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=200, null=True, verbose_name='Nombre ')),
                ('name_archive', models.CharField(blank=True, help_text='Nombre de archivo', max_length=200, null=True, verbose_name='Nombre de archivo')),
                ('age', models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año')),
                ('month', models.CharField(blank=True, help_text='Mes', max_length=50, null=True, verbose_name='Mes')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL Document')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ('PLaneacion',),
                'verbose_name_plural': 'PLaneacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagina',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagina',
            name='slug',
            field=models.CharField(blank=True, help_text='Slug', max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='titulo',
            field=models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='titulo',
            field=models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Configuracion.place')),
                ('serves_hot_dogs', models.BooleanField()),
                ('serves_pizza', models.BooleanField()),
            ],
            bases=('Configuracion.place',),
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(help_text='Modulo', on_delete=django.db.models.deletion.DO_NOTHING, to='Configuracion.module', verbose_name='Modulo')),
            ],
            options={
                'verbose_name': ('Sub modulo',),
                'verbose_name_plural': 'Sub modulo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', null=True, verbose_name='Descripción')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL Document')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(blank=True, help_text='Menu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Configuracion.menu', verbose_name='Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=200, null=True, verbose_name='Nombre ')),
                ('name_archive', models.CharField(blank=True, help_text='Nombre de archivo', max_length=200, null=True, verbose_name='Nombre de archivo')),
                ('age', models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año')),
                ('month', models.CharField(blank=True, help_text='Mes', max_length=50, null=True, verbose_name='Mes')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('orden', models.PositiveBigIntegerField(blank=True, help_text='Orden', null=True, verbose_name='Orden')),
                ('modulo', models.CharField(blank=True, choices=[('GENERAL', 'GENERAL'), ('MENSUAL', 'MENSUAL'), ('VIGENCIA', 'VIGENCIA'), ('ORDENANZAS', 'ORDENANZAS'), ('ACUERDOS', 'ACUERDOS'), ('CODIGOS', 'CODIGOS'), ('MANUALES', 'MANUALES'), ('POLITICAS', 'POLITICAS')], max_length=30, null=True, verbose_name='Estado:')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL Document')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('submodule', models.ForeignKey(blank=True, help_text='SubModulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Configuracion.submodule', verbose_name='Submodulo')),
            ],
            options={
                'verbose_name': ('Presupeusto',),
                'verbose_name_plural': 'Presupeusto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Configuracion.place')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, help_text='Titulo', null=True, verbose_name='Titulo')),
                ('slug', models.CharField(blank=True, help_text='Slug', max_length=100, null=True, verbose_name='Slug')),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('age', models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año')),
                ('month', models.CharField(blank=True, help_text='Mes', max_length=50, null=True, verbose_name='Mes')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ForeignKey(blank=True, help_text='Imagen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Configuracion.pagina', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre ', max_length=50, verbose_name='Nombre ')),
                ('imagen', models.ImageField(help_text='Imagen ', upload_to='', verbose_name='Imagen ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(blank=True, help_text='convocatoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Configuracion.convocatoria', verbose_name='convocatoria')),
                ('pagina', models.ForeignKey(blank=True, help_text='pagina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Configuracion.pagina', verbose_name='pagina')),
            ],
            options={
                'verbose_name': ('Imagen',),
                'verbose_name_plural': 'Imagen',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre ', max_length=100, verbose_name='Nombre ')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL Document')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(blank=True, help_text='convocatoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Configuracion.convocatoria', verbose_name='convocatoria')),
                ('pagina', models.ForeignKey(blank=True, help_text='pagina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Configuracion.pagina', verbose_name='pagina')),
                ('transparencia', models.ForeignKey(blank=True, help_text='transparencia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Configuracion.transparencia', verbose_name='transparencia')),
            ],
            options={
                'verbose_name': ('Imagen',),
                'verbose_name_plural': 'Imagen',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre ', max_length=200, null=True, verbose_name='Nombre ')),
                ('name_archive', models.CharField(blank=True, help_text='Nombre de archivo', max_length=200, null=True, verbose_name='Nombre de archivo')),
                ('age', models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año')),
                ('month', models.CharField(blank=True, help_text='Mes', max_length=50, null=True, verbose_name='Mes')),
                ('description', models.TextField(blank=True, help_text='Descripcion', null=True, verbose_name='Descripcion')),
                ('orden', models.PositiveBigIntegerField(blank=True, help_text='Orden', null=True, verbose_name='Orden')),
                ('modulo', models.CharField(blank=True, choices=[('PLANGENERAL', 'PLANGENERAL'), ('INFORMEFINAL', 'INFORMEFINAL'), ('PLANMEJORAMIENTO', 'PLANMEJORAMIENTO'), ('INFORMELEGAL', 'INFORMELEGAL'), ('REGISTRO', 'REGISTRO'), ('COMITE', 'COMITE'), ('MEJORAMIENTOAUDITORIA', 'MEJORAMIENTOAUDITORIA'), ('SEGUIMIENTOPLAN', 'SEGUIMIENTOPLAN'), ('SEGUIMIENTO', 'SEGUIMIENTO')], max_length=30, null=True, verbose_name='Estado:')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL Document')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('submodule', models.ForeignKey(blank=True, help_text='SubModulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Configuracion.submodule', verbose_name='Submodulo')),
            ],
            options={
                'verbose_name': ('Control Interno',),
                'verbose_name_plural': 'Control Interno',
                'ordering': ['id'],
            },
        ),
    ]
