# Generated by Django 3.1.1 on 2022-08-11 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprada', models.CharField(blank=True, choices=[('PAGO', 'PAGO'), ('NOPAGO', 'NOPAGO')], max_length=10, null=True, verbose_name='Comprada')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carro de compra',
                'verbose_name_plural': 'Carros de compra',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre municipio')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre')),
                ('validado', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=4, null=True, verbose_name='Validado:')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=254, null=True, verbose_name='Direccion')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('numero', models.CharField(blank=True, max_length=254, null=True, verbose_name='numero')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del país')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Nombre')),
                ('stock', models.CharField(max_length=254, verbose_name='Stock')),
                ('price', models.CharField(max_length=254, verbose_name='Precio ')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.ManyToManyField(blank=True, null=True, to='informacion.Comentario', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Redsocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre')),
                ('url', models.CharField(blank=True, max_length=254, null=True, verbose_name='Url')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre del departamento')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stakeholder',
                'verbose_name_plural': 'Stakeholders',
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de documento')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'TIpo de documentos',
            },
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Solucion', 'Solucion'), ('Servicio', 'Servicio')], max_length=10, null=True, verbose_name='TIpo:')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Nombre')),
                ('titulo', models.CharField(blank=True, max_length=254, null=True, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ManyToManyField(blank=True, null=True, to='informacion.Producto', verbose_name='Productos')),
                ('stakeholders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='informacion.stakeholder', verbose_name='Stakeholders')),
            ],
            options={
                'verbose_name': 'Solución',
                'verbose_name_plural': 'Soluciones',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Persona Natural', 'Persona Natural'), ('Persona Juridica', 'Persona Juridica')], max_length=100, null=True, verbose_name='Tipo de Persona:')),
                ('nit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nit')),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razón Social')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo electronico')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Apellidos')),
                ('identification', models.IntegerField(blank=True, null=True, verbose_name='Número de documento')),
                ('sex', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=10, null=True, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('type_house', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apartamento, unidad,edificio..')),
                ('neighbord', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='informacion.carshop')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='informacion.city', verbose_name='Municipio')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informacion.country', verbose_name='País')),
                ('historialcar', models.ManyToManyField(blank=True, null=True, related_name='Historial', to='informacion.CarShop')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='informacion.region', verbose_name='Departamento')),
                ('type_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='informacion.typedocument', verbose_name='Tipo de documento')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Productosdelcarro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='cantidad')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ManyToManyField(blank=True, null=True, to='informacion.Producto', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'productodelcarro',
                'verbose_name_plural': 'Productos del carro',
            },
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.CharField(blank=True, max_length=254, null=True, verbose_name='vision')),
                ('mision', models.CharField(blank=True, max_length=254, null=True, verbose_name='mision')),
                ('objetivos', models.TextField(blank=True, max_length=254, null=True, verbose_name='Objetivos')),
                ('descripcion', models.TextField(blank=True, max_length=254, null=True, verbose_name='Descripcion')),
                ('logourl', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='informacion.contacto', verbose_name='Contacto')),
                ('habilidades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='informacion.habilidad', verbose_name='habilidades')),
            ],
            options={
                'verbose_name': 'Información',
                'verbose_name_plural': 'Información',
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='redsocial',
            field=models.ManyToManyField(blank=True, null=True, to='informacion.Redsocial', verbose_name='Redes sociales'),
        ),
        migrations.AddField(
            model_name='carshop',
            name='productodelcarro',
            field=models.ManyToManyField(blank=True, null=True, to='informacion.Productosdelcarro', verbose_name='Productos'),
        ),
    ]
