# Generated by Django 3.1.1 on 2022-08-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshop',
            name='productodelcarro',
            field=models.ManyToManyField(to='informacion.Productosdelcarro', verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='redsocial',
            field=models.ManyToManyField(to='informacion.Redsocial', verbose_name='Redes sociales'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='comentarios',
            field=models.ManyToManyField(to='informacion.Comentario', verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='productosdelcarro',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='productosdelcarro',
            name='producto',
            field=models.ManyToManyField(to='informacion.Producto', verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='historialcar',
            field=models.ManyToManyField(related_name='Historial', to='informacion.CarShop'),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='producto',
            field=models.ManyToManyField(to='informacion.Producto', verbose_name='Productos'),
        ),
    ]
