# Generated by Django 3.2 on 2022-11-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0002_auto_20221110_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='age',
            field=models.CharField(blank=True, help_text='Año', max_length=100, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='descriptioncorta',
            field=models.TextField(blank=True, help_text='Descripcion Corta', null=True, verbose_name='Descripcion Corta'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='month',
            field=models.CharField(blank=True, help_text='Mes', max_length=50, null=True, verbose_name='Mes'),
        ),
    ]
