# Generated by Django 3.2 on 2022-11-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0003_auto_20221110_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='formato',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=30, null=True, verbose_name='Estado:'),
        ),
    ]
