# Generated by Django 3.2 on 2022-11-18 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0004_pagina_formato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='transparencia',
        ),
        migrations.AddField(
            model_name='submenu',
            name='transparencia',
            field=models.ForeignKey(blank=True, help_text='Menu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Configuracion.transparencia', verbose_name='Menu'),
        ),
    ]
